### ISSUE TITLE
this.$uuidKey() - is a method, not a property

### ISSUE THREAD

**Issue by aircokol** [estudioliver/vue-uuid#1]
Hi, thanks for your plugin.

However, I should notice, there is a mistake in the readme in the Usage section, method `this.$uuidKey()` should be used instead of property `this.$uuidKey` 
```
mounted() {
   console.log(this.$uuidKey()) // --> b9c9aa52-16b8-4745-a945-2846c81eeb82
}
```

**Comment by estudioliver** [comment]
Opss, thanks ... fixed
